# Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

require_relative '../lib/openapi'
require 'rack'

module OpenApiSDK
  class TestResponseBody < Minitest::Test

    def test_select_global_server
      record_test('servers-select-global-server-valid')

      sdk = SDK.new
      
      refute_nil sdk
      sdk.config_server_url(SERVERS[0], nil)


      res =  sdk.servers.select_global_server
      refute_nil res
      assert_equal(Rack::Utils.status_code(:ok), res.status_code)

    end

    def test_select_global_server_broken
      record_test('servers-select-global-server-broken')

      sdk = SDK.new
      refute_nil sdk

      sdk.config_server_url(SERVERS[1], nil)

      error = nil
      begin
        res = sdk.servers.select_global_server
      rescue => e
        error = e
      end

      refute_nil error
      assert_nil res
    end


    def test_select_server_with_id_default
      record_test('servers-select-server-with-id-default')

      sdk = SDK.new
      
      refute_nil sdk
      sdk.config_server_url(SERVERS[0], nil)

      res = sdk.servers.select_server_with_id()
      refute_nil res
      assert_equal(Rack::Utils.status_code(:ok), res.status_code)
    end


    def test_select_server_with_id_valid
      record_test('servers-select-server-with-id-valid')

      sdk = SDK.new
      
      refute_nil sdk
      sdk.config_server_url(SERVERS[0], nil)

      res = sdk.servers.select_server_with_id(server_url=Operations::SELECT_SERVER_WITH_ID_SERVERS[:SELECT_SERVER_WITH_ID_SERVER_VALID])

      refute_nil res
      assert_equal(Rack::Utils.status_code(:ok), res.status_code)
    end

    def test_select_server_with_id_broken
      record_test('servers-select-server-with-id-broken')

      sdk = OpenApiSDK::SDK.new
      
      refute_nil sdk
      sdk.config_server_url(SERVERS[0], nil)

      error = nil
      begin
        res = sdk.servers.select_server_with_id(server_url=Operations::SELECT_SERVER_WITH_ID_SERVERS[:SELECT_SERVER_WITH_ID_SERVER_BROKEN])
      rescue => e
        error = e
      end
      refute_nil error
      assert_nil res
    end

    def test_server_with_templates_global
      record_test('servers-server-with-templates-global')

      sdk = SDK.new
      
      refute_nil sdk
      sdk.config_server_url(SERVERS[2], {
        :hostname => "localhost",
        :port =>     "35123"
      })

      res = sdk.servers.server_with_templates_global
      refute_nil(res)
      assert_equal(Rack::Utils.status_code(:ok), res.status_code)
    end

    def test_server_with_templates
      record_test('servers-server-with-templates')

      sdk = SDK.new

      res = sdk.servers.server_with_templates(server_url=Utils::template_url(Operations::SERVER_WITH_TEMPLATES_SERVERS[0], {
        :hostname => "localhost",
        :port =>     "35123"
      }))
      refute_nil(res)
      assert_equal(Rack::Utils.status_code(:ok), res.status_code)
    end

  end
end
